version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: tutorial-postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./sql-ex-pg.sql:/docker-entrypoint-initdb.d/sql-ex-pg.sql
    env_file:
      - ./.env

volumes:
  postgres_data:
