version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: postgres_tutorial
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

volumes:
  postgres_data:
